/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/EdQGze8dUFV
 */

import { useEffect, useState } from "react";


export function Experience() {
  
  return (
    <div className="bg-white p-4">
      <div className="space-y-6">
        <div className="flex w-full gap-x-2 ">
          {/* <RingIcon strokeWidth={4} fill={"yellow"} blink={true}  className="px-1"/> */}

          <div className=" w-full">
          <div className="font-medium">Associate Software Engineer </div>
            
            <div className="mt-2">
            <div className="text-lg font-semibold">Accenture</div>
              <div className="text-sm text-gray-600">Full-time · Sept 2023 - Present · 6 mos</div>
              <div className="text-sm text-gray-600">Kolkata ,India</div>
              <div className="mt-2 text-sm">
                <div className="font-semibold">Development Consultant</div>
              </div>
              <div className="mt-2 text-sm font-medium text-blue-600">Business Development, Consulting,<br />Strategic Offering Management <br /> and Server Monitoring</div>
              <div className="text-sm text-gray-600"> Working On SAP </div>
            </div>
          </div>

        </div>
        <div>
        <div className="font-medium">Subject Matter Expert Python </div>
          <div className="mt-2">
          <div className="text-lg font-semibold">XcitEducation Foundations</div>
            <div className="text-sm text-gray-600">Intern · June 2022 -- Agust 2022 · 2 mos</div>
            <div className="text-sm text-gray-600">UP ,India</div>
            <div className="mt-2 text-sm">
              <div className="font-semibold">Teaching Python</div>
            </div>
            <div className="mt-2 text-sm font-medium text-blue-600">Structuring the curriculum,<br /> Creating and Curating content,<br />Hand-on instructor </div>
          </div>
        </div>
      </div>
    </div>
  )
}

  //@ts-ignore

function ChevronRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}

//@ts-ignore
function RingIcon(props) {
  const { size = 24, strokeWidth = 2, strokeColor = 'currentColor', fill = 'none', blink = false, blinkInterval = 500, ...otherProps } = props;
  const radius = size / 2 - strokeWidth / 2;
  const [isBlinking, setIsBlinking] = useState(blink);

  useEffect(() => {
      //@ts-ignore

    let intervalId;
    if (blink) {
      intervalId = setInterval(() => {
          //@ts-ignore

        setIsBlinking(prevState => !prevState);
      }, blinkInterval);
    }
      //@ts-ignore

    return () => clearInterval(intervalId);
  }, [blink, blinkInterval]);

  return (
    <svg width={size} height={size} viewBox={`0 0 ${size} ${size}`} {...otherProps}>
      {isBlinking ? (
        <circle cx={size / 2} cy={size / 2} r={radius} fill={strokeColor} />
      ) : (
        <circle cx={size / 2} cy={size / 2} r={radius} stroke={strokeColor} strokeWidth={strokeWidth} fill={fill} />
      )}
    </svg>
  );
}

